### ISSUE TITLE
hisql的每个数据库驱动都是各自写死的吗

### ISSUE THREAD

**Issue by xuejmnet** [tansar/HiSql#23]
可以替换掉connection，command，parameter吗或者用户实现替换DbProviderFactory

**Comment by tansar** [comment]
谢谢你的建议，每一个数据库实现都是与Hisql.dll 做了依赖隔离的  在HiSql中的AdoProvider中做了抽像化，在具体实现数据库的如HiSql.SqlServer做一些实现

**Comment by tansar** [comment]
@xuejmnet   暂时无法替换掉

**Comment by xuejmnet** [comment]
好的
