### ISSUE TITLE
不建议使用BinaryFormatter，避免不可控的安全

### ISSUE THREAD

**Issue by xljiulang** [tansar/HiSql#33]
https://github.com/tansar/HiSql/blob/master/HiSql/Utils/Serialize.cs#L26

BinaryFormatter风险：
https://docs.microsoft.com/zh-cn/dotnet/standard/serialization/binaryformatter-security-guide

**Comment by tansar** [comment]
谢谢提醒，这里是有这个风险，

**Comment by tansar** [comment]
已经修复 谢谢反馈
