### ISSUE TITLE
可能存在的代码逻辑严谨性低

### ISSUE THREAD

**Issue by xljiulang** [tansar/HiSql#34]
代码文件：
https://github.com/tansar/HiSql/blob/master/HiSql.SqlServer/SqlServerDM.cs#L56

分析：
``` c#
var attrTab = type.GetCustomAttributes().Where(a => a.GetType().Name == "HiTable").ToList();
...
 if (plist == null || plist.Count() == 0)  // plist==null 永远不成立
....
 foreach (Attribute pa in attrTab)
{
    hiTable = (HiTable)pa; ; // 还两个分号呢，不想想pa可能不是HiTable类型吗
    _hasTabAttr = true;
}
```

这里应该使用类型来过滤特性`type.GetCustomAttributes<HiTable>()`或者`type.GetCustomAttributes.OfType<HiTable>()`；
基本功还是要加强哈

**Comment by tansar** [comment]
关于你说 `不想想pa可能不是HiTable类型吗 `   你看看
`var attrTab = type.GetCustomAttributes().Where(a => a.GetType().Name == "HiTable").ToList();` 
这里就知道会不会其它的类型了 
两个分号的 谢谢提醒 这个后面会优化

**Comment by xljiulang** [comment]
你还是没明白，除了这个库，其他地方也可以有名字为hitable的类型吧，c#语言层没有哪里限制不同的程序集不能有相同类型名字呢

**Comment by xljiulang** [comment]
在dotnet里面，类型是唯一的，但是类型的名字不是唯一的，这个应该知晓吧

**Comment by tansar** [comment]
我明白你的意思，我已经用hi作为前辍，如果程序中引用的类与hitable相同 这是相冲突，  谢谢你的提醒，希望你能运行程序提出更有价值的问题 谢谢

**Comment by xljiulang** [comment]
我随便看看而已，随手挑挑几个质量性的小地方。个人觉得代码质量是写的时候就要考虑的，而不是修补出来的

**Comment by tansar** [comment]
谢谢你的建议， 代码质量确实重要，但也不是一次性能解决的， 有些小问题也是正常的，就像不太可能一次性写出完全没有BUG的程序一样
